baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Kaldi"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"

[params]
images = ["img/og-image.jpg"]